version: '3'
services:
  juiceshop:
    #build: .
    image: js
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=js_db
      - DB_USER=myuser
      - DB_PASS=mypassword

  db:
    image: postgres
    environment:
      - POSTGRES_DB=js_db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword